name: Deploy MkDocs site

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      # 1️⃣ Checkout the repo and allow pushing via GITHUB_TOKEN
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2️⃣ Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3️⃣ Install MkDocs and dependencies
      - run: pip install mkdocs-material pymdown-extensions

      # 4️⃣ Build the MkDocs site
      - run: mkdocs build

      # 5️⃣ Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      # 6️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4